/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/autenticacao/entrar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abre a sessão */
        post: operations["Entrar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/autenticacao/sair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Encerra a sessão */
        post: operations["Sair"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/autenticacao/trocar-senha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Troca a senha de quem está na sessão */
        post: operations["TrocarSenha"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/autenticacao/eu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quem está na sessão */
        get: operations["ConsultarSessao"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultas/cep/{cep}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Procura o endereço de um CEP
         * @description Serve para preencher o formulário, e nada depende dele: 503 quer dizer para digitar à mão, não que algo deu errado no cadastro.
         */
        get: operations["ConsultarCep"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultas/cnpj/{cnpj}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Procura razão social e endereço de um CNPJ
         * @description O CNPJ vai só com os dígitos: a barra da forma escrita seria outro trecho do endereço. Traz junto a situação cadastral na Receita, porque cadastrar cliente com empresa baixada é erro caro e quem digita à mão não tem como saber.
         */
        get: operations["ConsultarCnpj"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contratos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista os contratos recorrentes */
        get: operations["ListarContratos"];
        put?: never;
        /** Cria um contrato */
        post: operations["CriarContrato"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contratos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Abre um contrato */
        get: operations["ObterContrato"];
        /** Altera um contrato */
        put: operations["AlterarContrato"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contratos/gerar-mensalidades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gera as mensalidades de uma competência
         * @description Pode ser executado quantas vezes for preciso: o que já foi gerado é ignorado, não duplicado.
         */
        post: operations["GerarMensalidades"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/empresas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Empresas do tenant da sessão */
        get: operations["ListarEmpresas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pessoas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista as pessoas do tenant */
        get: operations["ListarPessoas"];
        put?: never;
        /** Cria um cadastro */
        post: operations["CriarPessoa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pessoas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Abre um cadastro */
        get: operations["ObterPessoa"];
        /** Altera um cadastro */
        put: operations["AlterarPessoa"];
        post?: never;
        /**
         * Inativa um cadastro
         * @description Não apaga: marca como inativo. Quem já apareceu em contrato ou cobrança precisa continuar existindo no histórico.
         */
        delete: operations["InativarPessoa"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pessoas/{id}/reativar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Desfaz a inativação
         * @description Existe como endereço próprio, e não como um PUT com ativo=true, porque o PUT reescreve o cadastro inteiro: a tela precisaria mandar de volta campos que ela não tem em mãos, e apagaria o que não conhece.
         */
        post: operations["ReativarPessoa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recebiveis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista os recebíveis */
        get: operations["ListarRecebiveis"];
        put?: never;
        /**
         * Lança uma cobrança fora de contrato
         * @description Para o que o escritório faz e não é mensalidade: declaração de imposto de renda, abertura de empresa, certidão. Fica sem contrato por trás.
         */
        post: operations["CriarRecebivelAvulso"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recebiveis/{id}/baixar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registra o recebimento */
        post: operations["BaixarRecebivel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recebiveis/{id}/cancelar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancela um recebível em aberto
         * @description Libera a competência para ser gerada de novo, sem apagar o histórico do que foi cancelado.
         */
        post: operations["CancelarRecebivel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recebiveis/{id}/estornar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Desfaz a baixa
         * @description Existe porque baixa errada acontece, e sem estorno a correção viraria um segundo registro inventado.
         */
        post: operations["EstornarRecebivel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estado da API
         * @description Devolve ambiente, versão e horário do servidor. Usado para verificar que o contrato entre API e front está fechado.
         */
        get: operations["ConsultarSaude"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ContratoDetalhado: {
            /** Format: uuid */
            id: string;
            codigo: string;
            /** Format: uuid */
            pessoaId: string;
            descricao: string;
            /** Format: double */
            valor: number;
            /** Format: int32 */
            diaDeVencimento: number;
            /** Format: date */
            inicioDaVigencia: string;
            /** Format: date */
            fimDaVigencia?: string | null;
            /** @enum {string} */
            situacao: "Ativo" | "Suspenso" | "Encerrado";
            observacoes: string;
        };
        ContratoNaLista: {
            /** Format: uuid */
            id: string;
            codigo: string;
            /** Format: uuid */
            pessoaId: string;
            codigoDaPessoa: string;
            nomeDaPessoa: string;
            descricao: string;
            /** Format: double */
            valor: number;
            /** Format: int32 */
            diaDeVencimento: number;
            /** @enum {string} */
            situacao: "Ativo" | "Suspenso" | "Encerrado";
        };
        DadosDaBaixa: {
            /** Format: double */
            valorPago: number;
            /** Format: date */
            pagoEm?: string | null;
        };
        DadosDeContrato: {
            /** Format: uuid */
            pessoaId: string;
            descricao?: string | null;
            /** Format: double */
            valor: number;
            /** Format: int32 */
            diaDeVencimento: number;
            /** Format: date */
            inicioDaVigencia: string;
            /** Format: date */
            fimDaVigencia?: string | null;
            /** @enum {string} */
            situacao: "Ativo" | "Suspenso" | "Encerrado";
            observacoes?: string | null;
        };
        DadosDeEndereco: {
            cep: string;
            logradouro: string;
            numero: string;
            complemento: string;
            bairro: string;
            cidade: string;
            uf: string;
        };
        DadosDePessoa: {
            /** @enum {string} */
            tipo: "Fisica" | "Juridica";
            /** @enum {string} */
            regimeTributario: "Mei" | "SimplesNacional" | "LucroPresumido" | "LucroReal" | "TerceiroSetor" | "PessoaFisica";
            responsavel?: string | null;
            papeis?: components["schemas"]["Papel"][] | null;
            nome?: string | null;
            nomeFantasia?: string | null;
            documento?: string | null;
            inscricaoEstadual?: string | null;
            inscricaoMunicipal?: string | null;
            email?: string | null;
            telefone?: string | null;
            celular?: string | null;
            endereco?: components["schemas"]["DadosDeEndereco"] | null;
            observacoes?: string | null;
            ativo: boolean;
        };
        DadosDoAvulso: {
            /** Format: uuid */
            pessoaId: string;
            descricao: string;
            /** Format: double */
            valor: number;
            /** Format: date */
            vencimento: string;
            /** Format: int32 */
            competenciaAno: number;
            /** Format: int32 */
            competenciaMes: number;
        };
        DadosDoCancelamento: {
            motivo?: string | null;
        };
        EmpresaDoCnpj: {
            cnpj: string;
            razaoSocial: string;
            nomeFantasia: string;
            situacao: string;
            logradouro: string;
            numero: string;
            complemento: string;
            bairro: string;
            cep: string;
            cidade: string;
            uf: string;
        };
        EmpresaNaLista: {
            /** Format: uuid */
            id: string;
            razaoSocial: string;
            nomeFantasia?: string | null;
            cnpj: string;
            ehMatriz: boolean;
        };
        EnderecoDoCep: {
            cep: string;
            logradouro: string;
            bairro: string;
            cidade: string;
            uf: string;
        };
        FalhaDeEntrada: {
            mensagem: string;
        };
        PaginaDeContratos: {
            itens: components["schemas"]["ContratoNaLista"][];
            /** Format: int32 */
            total: number;
            /** Format: int32 */
            pagina: number;
            /** Format: int32 */
            tamanho: number;
            /** Format: double */
            totalMensalAtivo: number;
        };
        PaginaDePessoas: {
            itens: components["schemas"]["PessoaNaLista"][];
            /** Format: int32 */
            total: number;
            /** Format: int32 */
            pagina: number;
            /** Format: int32 */
            tamanho: number;
        };
        PaginaDeRecebiveis: {
            itens: components["schemas"]["RecebivelNaLista"][];
            /** Format: int32 */
            total: number;
            /** Format: int32 */
            pagina: number;
            /** Format: int32 */
            tamanho: number;
            /** Format: double */
            totalEmAberto: number;
            /** Format: double */
            totalVencido: number;
            /** Format: double */
            totalRecebido: number;
        };
        /** @enum {string} */
        Papel: "Cliente" | "Fornecedor" | "Vendedor" | "Colaborador";
        PedidoDeEntrada: {
            email: string;
            senha: string;
        };
        PedidoDeGeracao: {
            /** Format: int32 */
            ano: number;
            /** Format: int32 */
            mes: number;
            contratoIds?: string[] | null;
        };
        PedidoDeTrocaDeSenha: {
            senhaAtual: string;
            senhaNova: string;
        };
        PessoaDetalhada: {
            /** Format: uuid */
            id: string;
            codigo: string;
            papeis: components["schemas"]["Papel"][];
            /** @enum {string} */
            regimeTributario: "Mei" | "SimplesNacional" | "LucroPresumido" | "LucroReal" | "TerceiroSetor" | "PessoaFisica";
            responsavel: string;
            /** @enum {string} */
            tipo: "Fisica" | "Juridica";
            nome: string;
            nomeFantasia: string;
            documento: string;
            inscricaoEstadual: string;
            inscricaoMunicipal: string;
            email: string;
            telefone: string;
            celular: string;
            endereco: components["schemas"]["DadosDeEndereco"];
            observacoes: string;
            ativo: boolean;
            /** Format: date-time */
            criadoEm: string;
        };
        PessoaNaLista: {
            /** Format: uuid */
            id: string;
            codigo: string;
            papeis: components["schemas"]["Papel"][];
            /** @enum {string} */
            tipo: "Fisica" | "Juridica";
            nome: string;
            nomeFantasia: string;
            documento: string;
            email: string;
            celular: string;
            cidade: string;
            uf: string;
            ativo: boolean;
        };
        Problema: {
            campo: string;
            titulo: string;
            descricao: string;
            sugestao: string;
        };
        RecebivelNaLista: {
            /** Format: uuid */
            id: string;
            codigoDaPessoa: string;
            nomeDaPessoa: string;
            descricao: string;
            /** Format: int32 */
            competenciaAno: number;
            /** Format: int32 */
            competenciaMes: number;
            /** Format: double */
            valor: number;
            /** Format: date */
            vencimento: string;
            /** @enum {string} */
            situacao: "Aberto" | "Pago" | "Cancelado";
            /** Format: double */
            valorPago?: number | null;
            /** Format: date */
            pagoEm?: string | null;
            origemDaBaixa: string;
            motivoDoCancelamento: string;
        };
        /** @enum {string} */
        RegimeTributario: "Mei" | "SimplesNacional" | "LucroPresumido" | "LucroReal" | "TerceiroSetor" | "PessoaFisica";
        RespostaComProblemas: {
            problemas: components["schemas"]["Problema"][];
        };
        RespostaSaude: {
            status: string;
            ambiente: string;
            versao: string;
            /** Format: date-time */
            momento: string;
        };
        ResultadoDaGeracao: {
            /** Format: int32 */
            geradas: number;
            /** Format: int32 */
            ignoradas: number;
            /** Format: int32 */
            foraDeVigencia: number;
            recado: string;
        };
        SessaoAberta: {
            nome: string;
            email: string;
            /** Format: uuid */
            tenantId: string;
            /** Format: date-time */
            expira: string;
        };
        SessaoAtual: {
            email: string;
            /** Format: uuid */
            tenantId: string;
            empresaId?: string | null;
        };
        /** @enum {string} */
        SituacaoContrato: "Ativo" | "Suspenso" | "Encerrado";
        /** @enum {string} */
        SituacaoRecebivel: "Aberto" | "Pago" | "Cancelado";
        /** @enum {string} */
        TipoPessoa: "Fisica" | "Juridica";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Entrar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PedidoDeEntrada"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessaoAberta"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FalhaDeEntrada"];
                };
            };
            /** @description Locked */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FalhaDeEntrada"];
                };
            };
        };
    };
    Sair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TrocarSenha: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PedidoDeTrocaDeSenha"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
        };
    };
    ConsultarSessao: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessaoAtual"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConsultarCep: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cep: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnderecoDoCep"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConsultarCnpj: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cnpj: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmpresaDoCnpj"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListarContratos: {
        parameters: {
            query?: {
                busca?: string;
                situacao?: components["schemas"]["SituacaoContrato"];
                pagina?: number;
                tamanho?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDeContratos"];
                };
            };
        };
    };
    CriarContrato: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DadosDeContrato"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContratoDetalhado"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
        };
    };
    ObterContrato: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContratoDetalhado"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AlterarContrato: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DadosDeContrato"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContratoDetalhado"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
        };
    };
    GerarMensalidades: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PedidoDeGeracao"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoDaGeracao"];
                };
            };
        };
    };
    ListarEmpresas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmpresaNaLista"][];
                };
            };
        };
    };
    ListarPessoas: {
        parameters: {
            query?: {
                busca?: string;
                papel?: components["schemas"]["Papel"];
                incluirInativos?: boolean;
                pagina?: number;
                tamanho?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDePessoas"];
                };
            };
        };
    };
    CriarPessoa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DadosDePessoa"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PessoaDetalhada"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
        };
    };
    ObterPessoa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PessoaDetalhada"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AlterarPessoa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DadosDePessoa"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PessoaDetalhada"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
        };
    };
    InativarPessoa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReativarPessoa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListarRecebiveis: {
        parameters: {
            query?: {
                situacao?: components["schemas"]["SituacaoRecebivel"];
                ano?: number;
                mes?: number;
                pagina?: number;
                tamanho?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDeRecebiveis"];
                };
            };
        };
    };
    CriarRecebivelAvulso: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DadosDoAvulso"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecebivelNaLista"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
        };
    };
    BaixarRecebivel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DadosDaBaixa"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecebivelNaLista"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
        };
    };
    CancelarRecebivel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DadosDoCancelamento"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecebivelNaLista"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
        };
    };
    EstornarRecebivel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecebivelNaLista"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConsultarSaude: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaSaude"];
                };
            };
        };
    };
}
