/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/autenticacao/entrar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abre a sessão */
        post: operations["Entrar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/autenticacao/sair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Encerra a sessão */
        post: operations["Sair"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/autenticacao/trocar-senha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Troca a senha de quem está na sessão */
        post: operations["TrocarSenha"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/autenticacao/eu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quem está na sessão */
        get: operations["ConsultarSessao"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultas/cep/{cep}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Procura o endereço de um CEP
         * @description Serve para preencher o formulário, e nada depende dele: 503 quer dizer para digitar à mão, não que algo deu errado no cadastro.
         */
        get: operations["ConsultarCep"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultas/cnpj/{cnpj}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Procura razão social e endereço de um CNPJ
         * @description O CNPJ vai só com os dígitos: a barra da forma escrita seria outro trecho do endereço. Traz junto a situação cadastral na Receita, porque cadastrar cliente com empresa baixada é erro caro e quem digita à mão não tem como saber.
         */
        get: operations["ConsultarCnpj"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contas-bancarias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista as contas do escritório, com o saldo
         * @description As ativas primeiro, e dentro de cada grupo pelo nome. O saldo atual é o inicial mais os movimentos, somado no banco. Um escritório tem poucas contas: a lista vem inteira, sem página.
         */
        get: operations["ListarContasBancarias"];
        put?: never;
        /** Cadastra uma conta */
        post: operations["CriarContaBancaria"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contas-bancarias/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Altera uma conta
         * @description Também inativa, reativa e marca a conta que recebe as cobranças do PSP. Conta não se apaga, e o saldo inicial não muda depois do primeiro movimento.
         */
        put: operations["AlterarContaBancaria"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contratos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista os contratos recorrentes */
        get: operations["ListarContratos"];
        put?: never;
        /** Cria um contrato */
        post: operations["CriarContrato"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contratos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Abre um contrato */
        get: operations["ObterContrato"];
        /** Altera um contrato */
        put: operations["AlterarContrato"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contratos/gerar-mensalidades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gera as mensalidades de uma competência
         * @description Pode ser executado quantas vezes for preciso: o que já foi gerado é ignorado, não duplicado.
         */
        post: operations["GerarMensalidades"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/empresas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Empresas do tenant da sessão */
        get: operations["ListarEmpresas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/empresas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Corrige os dados do estabelecimento
         * @description O provisionamento grava razão social e CNPJ uma vez, a partir de variável de ambiente. Sem isto, um dígito errado ali não teria conserto pela aplicação.
         */
        put: operations["AlterarEmpresa"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lancamentos/{id}/cobrar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Emite boleto e Pix para um lançamento
         * @description Cria a cobrança no PSP e guarda o link onde o cliente escolhe entre boleto e Pix. Recusa cobrar duas vezes o mesmo lançamento: a segunda emissão não substituiria a primeira, e o cliente receberia dois boletos.
         */
        post: operations["CobrarLancamento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cobrancas/divergencias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pagamentos do PSP que não puderam ser aplicados
         * @description Os avisos de pagamento que chegaram para lançamentos que já não estavam em aberto. Decidir entre devolver o valor e reabrir o título é trabalho de gente.
         */
        get: operations["ListarDivergenciasDeCobranca"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lancamentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista os lançamentos */
        get: operations["ListarLancamentos"];
        put?: never;
        /**
         * Lança um valor fora de contrato, a receber ou a pagar
         * @description A receber, para o que o escritório faz e não é mensalidade: declaração de imposto de renda, abertura de empresa, certidão. A pagar, para as contas do próprio escritório. A natureza é obrigatória, e a pessoa precisa ter o papel que ela pede: cliente para receber, fornecedor para pagar.
         */
        post: operations["CriarLancamentoAvulso"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lancamentos/{id}/baixar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registra a baixa
         * @description Exige a conta onde o dinheiro entrou ou de onde saiu, e grava o movimento nela junto com a baixa.
         */
        post: operations["BaixarLancamento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lancamentos/{id}/cancelar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancela um lançamento em aberto
         * @description Libera a competência para ser gerada de novo, sem apagar o histórico do que foi cancelado.
         */
        post: operations["CancelarLancamento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lancamentos/{id}/estornar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Desfaz a baixa
         * @description Existe porque baixa errada acontece, e sem estorno a correção viraria um segundo registro inventado.
         */
        post: operations["EstornarLancamento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lancamentos/parcelamentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lança um valor dividido em parcelas mensais
         * @description Os centavos que sobram da divisão vão para a primeira parcela, e cada vencimento parte da primeira data. Com uma parcela só, é um lançamento avulso comum.
         */
        post: operations["ParcelarLancamento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lancamentos/{id}/renegociar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Troca um título em aberto por parcelas novas
         * @description O título original vira renegociado e continua ocupando a competência; as parcelas novas apontam para ele. Juros e multa acrescentam, desconto abate.
         */
        post: operations["RenegociarLancamento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lancamentos/baixar-em-lote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registra a baixa de vários lançamentos de uma vez
         * @description Cada lançamento é baixado ou recusado por conta própria: um já pago não impede os outros. O valor baixado é o valor do lançamento.
         */
        post: operations["BaixarLancamentosEmLote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pessoas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista as pessoas do tenant */
        get: operations["ListarPessoas"];
        put?: never;
        /** Cria um cadastro */
        post: operations["CriarPessoa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pessoas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Abre um cadastro */
        get: operations["ObterPessoa"];
        /** Altera um cadastro */
        put: operations["AlterarPessoa"];
        post?: never;
        /**
         * Inativa um cadastro
         * @description Não apaga: marca como inativo. Quem já apareceu em contrato ou cobrança precisa continuar existindo no histórico. Recusa enquanto houver contrato não encerrado ou cobrança em aberto.
         */
        delete: operations["InativarPessoa"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pessoas/{id}/reativar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Desfaz a inativação
         * @description Existe como endereço próprio, e não como um PUT com ativo=true, porque o PUT reescreve o cadastro inteiro: a tela precisaria mandar de volta campos que ela não tem em mãos, e apagaria o que não conhece.
         */
        post: operations["ReativarPessoa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estado da API
         * @description Devolve ambiente, versão e horário do servidor. Usado para verificar que o contrato entre API e front está fechado.
         */
        get: operations["ConsultarSaude"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ContaNaLista: {
            /** Format: uuid */
            id: string;
            nome: string;
            /** @enum {string} */
            tipo: "Corrente" | "Poupanca" | "Pagamento" | "Dinheiro";
            banco: string;
            agencia: string;
            numero: string;
            /** Format: double */
            saldoInicial: number;
            /** Format: date */
            saldoInicialEm: string;
            /** Format: double */
            saldoAtual: number;
            ativa: boolean;
            recebeCobrancas: boolean;
            temMovimentos: boolean;
        };
        ContratoDetalhado: {
            /** Format: uuid */
            id: string;
            codigo: string;
            /** Format: uuid */
            pessoaId: string;
            descricao: string;
            /** Format: double */
            valor: number;
            /** Format: int32 */
            diaDeVencimento: number;
            /** Format: date */
            inicioDaVigencia: string;
            /** Format: date */
            fimDaVigencia?: string | null;
            /** @enum {string} */
            situacao: "Ativo" | "Suspenso" | "Encerrado";
            observacoes: string;
        };
        ContratoNaLista: {
            /** Format: uuid */
            id: string;
            codigo: string;
            /** Format: uuid */
            pessoaId: string;
            codigoDaPessoa: string;
            nomeDaPessoa: string;
            descricao: string;
            /** Format: double */
            valor: number;
            /** Format: int32 */
            diaDeVencimento: number;
            /** @enum {string} */
            situacao: "Ativo" | "Suspenso" | "Encerrado";
        };
        DadosDaBaixa: {
            /** Format: uuid */
            contaId: string;
            /** Format: double */
            valorPago: number;
            /** Format: date */
            pagoEm?: string | null;
        };
        DadosDaBaixaEmLote: {
            /** Format: uuid */
            contaId: string;
            ids?: string[] | null;
            /** Format: date */
            pagoEm?: string | null;
        };
        DadosDaConta: {
            nome?: string | null;
            /** @enum {string} */
            tipo: "Corrente" | "Poupanca" | "Pagamento" | "Dinheiro";
            banco?: string | null;
            agencia?: string | null;
            numero?: string | null;
            /** Format: double */
            saldoInicial: number;
            /** Format: date */
            saldoInicialEm?: string | null;
            ativa: boolean;
            recebeCobrancas: boolean;
        };
        DadosDaRenegociacao: {
            /** Format: int32 */
            parcelas: number;
            /** Format: date */
            primeiroVencimento: string;
            /** Format: double */
            juros: number;
            /** Format: double */
            multa: number;
            /** Format: double */
            desconto: number;
            motivo?: string | null;
        };
        DadosDeContrato: {
            /** Format: uuid */
            pessoaId: string;
            descricao?: string | null;
            /** Format: double */
            valor: number;
            /** Format: int32 */
            diaDeVencimento: number;
            /** Format: date */
            inicioDaVigencia: string;
            /** Format: date */
            fimDaVigencia?: string | null;
            /** @enum {string} */
            situacao: "Ativo" | "Suspenso" | "Encerrado";
            observacoes?: string | null;
        };
        DadosDeEmpresa: {
            razaoSocial?: string | null;
            nomeFantasia?: string | null;
            cnpj?: string | null;
        };
        DadosDeEndereco: {
            cep: string;
            logradouro: string;
            numero: string;
            complemento: string;
            bairro: string;
            cidade: string;
            uf: string;
        };
        DadosDePessoa: {
            /** @enum {string} */
            tipo: "Fisica" | "Juridica";
            /** @enum {string} */
            regimeTributario: "Mei" | "SimplesNacional" | "LucroPresumido" | "LucroReal" | "TerceiroSetor" | "PessoaFisica";
            responsavel?: string | null;
            papeis?: components["schemas"]["Papel"][] | null;
            nome?: string | null;
            nomeFantasia?: string | null;
            documento?: string | null;
            inscricaoEstadual?: string | null;
            inscricaoMunicipal?: string | null;
            email?: string | null;
            telefone?: string | null;
            celular?: string | null;
            endereco?: components["schemas"]["DadosDeEndereco"] | null;
            observacoes?: string | null;
            ativo: boolean;
        };
        DadosDoAvulso: {
            /** @enum {string} */
            natureza: "Receber" | "Pagar";
            /** Format: uuid */
            pessoaId: string;
            descricao: string;
            /** Format: double */
            valor: number;
            /** Format: date */
            vencimento: string;
            /** Format: int32 */
            competenciaAno: number;
            /** Format: int32 */
            competenciaMes: number;
        };
        DadosDoCancelamento: {
            motivo?: string | null;
        };
        DadosDoParcelamento: {
            /** @enum {string} */
            natureza: "Receber" | "Pagar";
            /** Format: uuid */
            pessoaId: string;
            descricao: string;
            /** Format: double */
            valorTotal: number;
            /** Format: int32 */
            parcelas: number;
            /** Format: date */
            primeiroVencimento: string;
            /** Format: int32 */
            competenciaAno: number;
            /** Format: int32 */
            competenciaMes: number;
        };
        /** @enum {string} */
        Direcao: "Crescente" | "Decrescente";
        DivergenciaDeCobranca: {
            eventoId: string;
            /** Format: uuid */
            lancamentoId?: string | null;
            tipo: string;
            divergencia: string;
            /** Format: date-time */
            recebidoEm: string;
            nomeDaPessoa?: string | null;
            descricao?: string | null;
            /** Format: double */
            valor?: number | null;
        };
        EmpresaDoCnpj: {
            cnpj: string;
            razaoSocial: string;
            nomeFantasia: string;
            situacao: string;
            logradouro: string;
            numero: string;
            complemento: string;
            bairro: string;
            cep: string;
            cidade: string;
            uf: string;
        };
        EmpresaNaLista: {
            /** Format: uuid */
            id: string;
            razaoSocial: string;
            nomeFantasia?: string | null;
            cnpj: string;
            ehMatriz: boolean;
        };
        EnderecoDoCep: {
            cep: string;
            logradouro: string;
            bairro: string;
            cidade: string;
            uf: string;
        };
        FalhaDeEntrada: {
            mensagem: string;
        };
        LancamentoCobrado: {
            /** Format: uuid */
            id: string;
            cobrancaId: string;
            cobrancaUrl: string;
        };
        LancamentoNaLista: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            natureza: "Receber" | "Pagar";
            codigoDaPessoa: string;
            nomeDaPessoa: string;
            descricao: string;
            /** Format: int32 */
            competenciaAno: number;
            /** Format: int32 */
            competenciaMes: number;
            /** Format: double */
            valor: number;
            /** Format: date */
            vencimento: string;
            /** @enum {string} */
            situacao: "Aberto" | "Pago" | "Cancelado" | "Renegociado";
            /** Format: double */
            valorPago?: number | null;
            /** Format: date */
            pagoEm?: string | null;
            origemDaBaixa: string;
            motivoDoCancelamento: string;
            /** Format: int32 */
            parcelaNumero?: number | null;
            /** Format: int32 */
            parcelasTotal?: number | null;
            /** Format: uuid */
            renegociadoDeId?: string | null;
            cobrancaUrl: string;
            contaDaBaixa?: string | null;
        };
        /** @enum {string} */
        NaturezaLancamento: "Receber" | "Pagar";
        /** @enum {string} */
        OrdemDeContratos: "Codigo" | "Cliente" | "Valor" | "Vencimento";
        /** @enum {string} */
        OrdemDeLancamentos: "Vencimento" | "Pessoa" | "Competencia" | "Valor";
        /** @enum {string} */
        OrdemDePessoas: "Nome" | "Codigo";
        PaginaDeContratos: {
            itens: components["schemas"]["ContratoNaLista"][];
            /** Format: int32 */
            total: number;
            /** Format: int32 */
            pagina: number;
            /** Format: int32 */
            tamanho: number;
            /** Format: double */
            totalMensalAtivo: number;
        };
        PaginaDeLancamentos: {
            itens: components["schemas"]["LancamentoNaLista"][];
            /** Format: int32 */
            total: number;
            /** Format: int32 */
            pagina: number;
            /** Format: int32 */
            tamanho: number;
            /** Format: double */
            totalEmAberto: number;
            /** Format: double */
            totalVencido: number;
            /** Format: double */
            totalPago: number;
        };
        PaginaDePessoas: {
            itens: components["schemas"]["PessoaNaLista"][];
            /** Format: int32 */
            total: number;
            /** Format: int32 */
            pagina: number;
            /** Format: int32 */
            tamanho: number;
        };
        /** @enum {string} */
        Papel: "Cliente" | "Fornecedor" | "Vendedor" | "Colaborador";
        ParcelamentoCriado: {
            /** Format: uuid */
            parcelamentoId?: string | null;
            parcelas: components["schemas"]["LancamentoNaLista"][];
        };
        PedidoDeEntrada: {
            email: string;
            senha: string;
        };
        PedidoDeGeracao: {
            /** Format: int32 */
            ano: number;
            /** Format: int32 */
            mes: number;
            contratoIds?: string[] | null;
        };
        PedidoDeTrocaDeSenha: {
            senhaAtual: string;
            senhaNova: string;
        };
        PessoaDetalhada: {
            /** Format: uuid */
            id: string;
            codigo: string;
            papeis: components["schemas"]["Papel"][];
            /** @enum {string} */
            regimeTributario: "Mei" | "SimplesNacional" | "LucroPresumido" | "LucroReal" | "TerceiroSetor" | "PessoaFisica";
            responsavel: string;
            /** @enum {string} */
            tipo: "Fisica" | "Juridica";
            nome: string;
            nomeFantasia: string;
            documento: string;
            inscricaoEstadual: string;
            inscricaoMunicipal: string;
            email: string;
            telefone: string;
            celular: string;
            endereco: components["schemas"]["DadosDeEndereco"];
            observacoes: string;
            ativo: boolean;
            /** Format: date-time */
            criadoEm: string;
        };
        PessoaNaLista: {
            /** Format: uuid */
            id: string;
            codigo: string;
            papeis: components["schemas"]["Papel"][];
            /** @enum {string} */
            tipo: "Fisica" | "Juridica";
            nome: string;
            nomeFantasia: string;
            documento: string;
            email: string;
            telefone: string;
            celular: string;
            endereco: components["schemas"]["DadosDeEndereco"];
            ativo: boolean;
        };
        Problema: {
            campo: string;
            titulo: string;
            descricao: string;
            sugestao: string;
        };
        RecusaNaBaixaEmLote: {
            /** Format: uuid */
            id: string;
            motivo: string;
        };
        /** @enum {string} */
        RegimeTributario: "Mei" | "SimplesNacional" | "LucroPresumido" | "LucroReal" | "TerceiroSetor" | "PessoaFisica";
        RenegociacaoCriada: {
            /** Format: uuid */
            renegociacaoId: string;
            /** Format: uuid */
            origemId: string;
            parcelas: components["schemas"]["LancamentoNaLista"][];
        };
        RespostaComProblemas: {
            problemas: components["schemas"]["Problema"][];
        };
        RespostaSaude: {
            status: string;
            ambiente: string;
            versao: string;
            /** Format: date-time */
            momento: string;
        };
        ResultadoDaBaixaEmLote: {
            /** Format: int32 */
            baixados: number;
            recusados: components["schemas"]["RecusaNaBaixaEmLote"][];
        };
        ResultadoDaGeracao: {
            /** Format: int32 */
            geradas: number;
            /** Format: int32 */
            ignoradas: number;
            /** Format: int32 */
            foraDeVigencia: number;
            recado: string;
        };
        SessaoAberta: {
            nome: string;
            email: string;
            /** Format: uuid */
            tenantId: string;
            /** Format: date-time */
            expira: string;
        };
        SessaoAtual: {
            email: string;
            /** Format: uuid */
            tenantId: string;
            empresaId?: string | null;
        };
        /** @enum {string} */
        SituacaoContrato: "Ativo" | "Suspenso" | "Encerrado";
        /** @enum {string} */
        SituacaoLancamento: "Aberto" | "Pago" | "Cancelado" | "Renegociado";
        /** @enum {string} */
        TipoConta: "Corrente" | "Poupanca" | "Pagamento" | "Dinheiro";
        /** @enum {string} */
        TipoPessoa: "Fisica" | "Juridica";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Entrar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PedidoDeEntrada"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessaoAberta"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FalhaDeEntrada"];
                };
            };
            /** @description Locked */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FalhaDeEntrada"];
                };
            };
        };
    };
    Sair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TrocarSenha: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PedidoDeTrocaDeSenha"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
        };
    };
    ConsultarSessao: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessaoAtual"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConsultarCep: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cep: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnderecoDoCep"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConsultarCnpj: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cnpj: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmpresaDoCnpj"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListarContasBancarias: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContaNaLista"][];
                };
            };
        };
    };
    CriarContaBancaria: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DadosDaConta"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContaNaLista"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
        };
    };
    AlterarContaBancaria: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DadosDaConta"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContaNaLista"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
        };
    };
    ListarContratos: {
        parameters: {
            query?: {
                busca?: string;
                situacao?: components["schemas"]["SituacaoContrato"];
                pagina?: number;
                tamanho?: number;
                ordenarPor?: "Codigo" | "Cliente" | "Valor" | "Vencimento";
                direcao?: "Crescente" | "Decrescente";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDeContratos"];
                };
            };
        };
    };
    CriarContrato: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DadosDeContrato"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContratoDetalhado"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
        };
    };
    ObterContrato: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContratoDetalhado"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AlterarContrato: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DadosDeContrato"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContratoDetalhado"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
        };
    };
    GerarMensalidades: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PedidoDeGeracao"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoDaGeracao"];
                };
            };
        };
    };
    ListarEmpresas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmpresaNaLista"][];
                };
            };
        };
    };
    AlterarEmpresa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DadosDeEmpresa"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmpresaNaLista"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
        };
    };
    CobrarLancamento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LancamentoCobrado"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
        };
    };
    ListarDivergenciasDeCobranca: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DivergenciaDeCobranca"][];
                };
            };
        };
    };
    ListarLancamentos: {
        parameters: {
            query?: {
                natureza?: "Receber" | "Pagar";
                situacao?: components["schemas"]["SituacaoLancamento"];
                ano?: number;
                mes?: number;
                busca?: string;
                vencimentoDe?: string;
                vencimentoAte?: string;
                pagina?: number;
                tamanho?: number;
                ordenarPor?: "Vencimento" | "Pessoa" | "Competencia" | "Valor";
                direcao?: "Crescente" | "Decrescente";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDeLancamentos"];
                };
            };
        };
    };
    CriarLancamentoAvulso: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DadosDoAvulso"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LancamentoNaLista"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
        };
    };
    BaixarLancamento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DadosDaBaixa"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LancamentoNaLista"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
        };
    };
    CancelarLancamento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DadosDoCancelamento"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LancamentoNaLista"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
        };
    };
    EstornarLancamento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LancamentoNaLista"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ParcelarLancamento: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DadosDoParcelamento"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParcelamentoCriado"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
        };
    };
    RenegociarLancamento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DadosDaRenegociacao"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenegociacaoCriada"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
        };
    };
    BaixarLancamentosEmLote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DadosDaBaixaEmLote"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoDaBaixaEmLote"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
        };
    };
    ListarPessoas: {
        parameters: {
            query?: {
                busca?: string;
                papel?: components["schemas"]["Papel"];
                incluirInativos?: boolean;
                pagina?: number;
                tamanho?: number;
                ordenarPor?: "Nome" | "Codigo";
                direcao?: "Crescente" | "Decrescente";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDePessoas"];
                };
            };
        };
    };
    CriarPessoa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DadosDePessoa"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PessoaDetalhada"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
        };
    };
    ObterPessoa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PessoaDetalhada"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AlterarPessoa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DadosDePessoa"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PessoaDetalhada"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
        };
    };
    InativarPessoa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaComProblemas"];
                };
            };
        };
    };
    ReativarPessoa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConsultarSaude: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespostaSaude"];
                };
            };
        };
    };
}
