// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexo.Api.Dados;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexo.Api.Dados.Migracoes
{
    [DbContext(typeof(NexoDbContext))]
    [Migration("20260916021543_ValorDoContratoComVigencia")]
    partial class ValorDoContratoComVigencia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Nexo.Api.Dominio.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Natureza")
                        .HasColumnType("integer")
                        .HasColumnName("natureza");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nome");

                    b.Property<Guid?>("PaiId")
                        .HasColumnType("uuid")
                        .HasColumnName("pai_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.HasIndex("PaiId")
                        .HasDatabaseName("ix_categorias_pai_id");

                    b.HasIndex("TenantId", "PaiId")
                        .HasDatabaseName("ix_categorias_tenant_id_pai_id");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("Nexo.Api.Dominio.CentroDeCusto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nome");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_centros_de_custo");

                    b.HasIndex("TenantId", "Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_centros_de_custo_tenant_id_nome");

                    b.ToTable("centros_de_custo", (string)null);
                });

            modelBuilder.Entity("Nexo.Api.Dominio.ContaBancaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("agencia");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("banco");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.Property<bool>("RecebeCobrancas")
                        .HasColumnType("boolean")
                        .HasColumnName("recebe_cobrancas");

                    b.Property<decimal>("SaldoInicial")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("saldo_inicial");

                    b.Property<DateOnly>("SaldoInicialEm")
                        .HasColumnType("date")
                        .HasColumnName("saldo_inicial_em");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_contas_bancarias");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_contas_bancarias_tenant_id")
                        .HasFilter("recebe_cobrancas");

                    b.HasIndex("TenantId", "Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_contas_bancarias_tenant_id_nome");

                    b.ToTable("contas_bancarias", (string)null);
                });

            modelBuilder.Entity("Nexo.Api.Dominio.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<int>("DiaDeVencimento")
                        .HasColumnType("integer")
                        .HasColumnName("dia_de_vencimento");

                    b.Property<DateOnly?>("FimDaVigencia")
                        .HasColumnType("date")
                        .HasColumnName("fim_da_vigencia");

                    b.Property<DateOnly>("InicioDaVigencia")
                        .HasColumnType("date")
                        .HasColumnName("inicio_da_vigencia");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("observacoes");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_contratos");

                    b.HasIndex("PessoaId")
                        .HasDatabaseName("ix_contratos_pessoa_id");

                    b.HasIndex("TenantId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_contratos_tenant_id_codigo");

                    b.HasIndex("TenantId", "PessoaId")
                        .HasDatabaseName("ix_contratos_tenant_id_pessoa_id");

                    b.ToTable("contratos", (string)null);
                });

            modelBuilder.Entity("Nexo.Api.Dominio.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("MatrizId")
                        .HasColumnType("uuid")
                        .HasColumnName("matriz_id");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razao_social");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_empresas");

                    b.HasIndex("MatrizId")
                        .HasDatabaseName("ix_empresas_matriz_id");

                    b.HasIndex("TenantId", "Cnpj")
                        .IsUnique()
                        .HasDatabaseName("ix_empresas_tenant_id_cnpj");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("Nexo.Api.Dominio.EventoDeAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Acao")
                        .HasColumnType("integer")
                        .HasColumnName("acao");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("autor");

                    b.Property<Guid?>("ContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_id");

                    b.Property<DateTimeOffset>("Em")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("em");

                    b.Property<int>("Entidade")
                        .HasColumnType("integer")
                        .HasColumnName("entidade");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidade_id");

                    b.Property<Guid?>("LancamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("lancamento_id");

                    b.Property<string>("Mudancas")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("mudancas");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_eventos_de_auditoria");

                    b.HasIndex("TenantId", "ContaId", "Em")
                        .HasDatabaseName("ix_eventos_de_auditoria_tenant_id_conta_id_em");

                    b.HasIndex("TenantId", "LancamentoId", "Em")
                        .HasDatabaseName("ix_eventos_de_auditoria_tenant_id_lancamento_id_em");

                    b.ToTable("eventos_de_auditoria", (string)null);
                });

            modelBuilder.Entity("Nexo.Api.Dominio.EventoDeCobranca", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("id");

                    b.Property<string>("Divergencia")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("divergencia");

                    b.Property<Guid?>("LancamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("lancamento_id");

                    b.Property<DateTimeOffset>("RecebidoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recebido_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("tipo");

                    b.HasKey("TenantId", "Id")
                        .HasName("pk_eventos_de_cobranca");

                    b.HasIndex("TenantId", "LancamentoId")
                        .HasDatabaseName("ix_eventos_de_cobranca_tenant_id_lancamento_id");

                    b.ToTable("eventos_de_cobranca", (string)null);
                });

            modelBuilder.Entity("Nexo.Api.Dominio.Lancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<Guid?>("CentroDeCustoId")
                        .HasColumnType("uuid")
                        .HasColumnName("centro_de_custo_id");

                    b.Property<string>("CobrancaId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("cobranca_id");

                    b.Property<string>("CobrancaUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("cobranca_url");

                    b.Property<int>("CompetenciaAno")
                        .HasColumnType("integer")
                        .HasColumnName("competencia_ano");

                    b.Property<int>("CompetenciaMes")
                        .HasColumnType("integer")
                        .HasColumnName("competencia_mes");

                    b.Property<Guid?>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("Desconto")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("desconto");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<decimal?>("Juros")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("juros");

                    b.Property<string>("MotivoDoCancelamento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo_do_cancelamento");

                    b.Property<decimal?>("Multa")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("multa");

                    b.Property<int>("Natureza")
                        .HasColumnType("integer")
                        .HasColumnName("natureza");

                    b.Property<string>("OrigemDaBaixa")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("origem_da_baixa");

                    b.Property<DateOnly?>("PagoEm")
                        .HasColumnType("date")
                        .HasColumnName("pago_em");

                    b.Property<int?>("ParcelaNumero")
                        .HasColumnType("integer")
                        .HasColumnName("parcela_numero");

                    b.Property<Guid?>("ParcelamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("parcelamento_id");

                    b.Property<int?>("ParcelasTotal")
                        .HasColumnType("integer")
                        .HasColumnName("parcelas_total");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<Guid?>("RecorrenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorrencia_id");

                    b.Property<Guid?>("RenegociadoDeId")
                        .HasColumnType("uuid")
                        .HasColumnName("renegociado_de_id");

                    b.Property<int>("Situacao")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Valor")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor");

                    b.Property<decimal?>("ValorPago")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor_pago");

                    b.Property<DateOnly>("Vencimento")
                        .HasColumnType("date")
                        .HasColumnName("vencimento");

                    b.HasKey("Id")
                        .HasName("pk_lancamentos");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_lancamentos_categoria_id");

                    b.HasIndex("CentroDeCustoId")
                        .HasDatabaseName("ix_lancamentos_centro_de_custo_id");

                    b.HasIndex("ContratoId")
                        .HasDatabaseName("ix_lancamentos_contrato_id");

                    b.HasIndex("PessoaId")
                        .HasDatabaseName("ix_lancamentos_pessoa_id");

                    b.HasIndex("RecorrenciaId")
                        .HasDatabaseName("ix_lancamentos_recorrencia_id");

                    b.HasIndex("RenegociadoDeId")
                        .HasDatabaseName("ix_lancamentos_renegociado_de_id");

                    b.HasIndex("TenantId", "CategoriaId")
                        .HasDatabaseName("ix_lancamentos_tenant_id_categoria_id");

                    b.HasIndex("TenantId", "CentroDeCustoId")
                        .HasDatabaseName("ix_lancamentos_tenant_id_centro_de_custo_id");

                    b.HasIndex("TenantId", "ParcelamentoId")
                        .HasDatabaseName("ix_lancamentos_tenant_id_parcelamento_id");

                    b.HasIndex("TenantId", "ContratoId", "CompetenciaAno", "CompetenciaMes")
                        .IsUnique()
                        .HasDatabaseName("ix_lancamentos_tenant_id_contrato_id_competencia_ano_competenc")
                        .HasFilter("situacao <> 3");

                    b.HasIndex("TenantId", "Natureza", "Situacao", "Vencimento")
                        .HasDatabaseName("ix_lancamentos_tenant_id_natureza_situacao_vencimento");

                    b.HasIndex("TenantId", "RecorrenciaId", "CompetenciaAno", "CompetenciaMes")
                        .IsUnique()
                        .HasDatabaseName("ix_lancamentos_tenant_id_recorrencia_id_competencia_ano_compet")
                        .HasFilter("situacao <> 3");

                    b.ToTable("lancamentos", (string)null);
                });

            modelBuilder.Entity("Nexo.Api.Dominio.MovimentoDeConta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<Guid?>("LancamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("lancamento_id");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("origem");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TransferenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("transferencia_id");

                    b.Property<decimal>("Valor")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_movimentos_de_conta");

                    b.HasIndex("ContaId")
                        .HasDatabaseName("ix_movimentos_de_conta_conta_id");

                    b.HasIndex("LancamentoId")
                        .IsUnique()
                        .HasDatabaseName("ix_movimentos_de_conta_lancamento_id")
                        .HasFilter("lancamento_id IS NOT NULL AND origem = 'baixa'");

                    b.HasIndex("TransferenciaId")
                        .HasDatabaseName("ix_movimentos_de_conta_transferencia_id");

                    b.HasIndex("TenantId", "ContaId", "Data")
                        .HasDatabaseName("ix_movimentos_de_conta_tenant_id_conta_id_data");

                    b.ToTable("movimentos_de_conta", (string)null);
                });

            modelBuilder.Entity("Nexo.Api.Dominio.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("celular");

                    b.Property<string>("ClienteNoAsaas")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("cliente_no_asaas");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("InscricaoEstadual")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("inscricao_estadual");

                    b.Property<string>("InscricaoMunicipal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("inscricao_municipal");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("observacoes");

                    b.Property<int>("RegimeTributario")
                        .HasColumnType("integer")
                        .HasColumnName("regime_tributario");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("responsavel");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_pessoas");

                    b.HasIndex("TenantId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_pessoas_tenant_id_codigo");

                    b.HasIndex("TenantId", "Documento")
                        .IsUnique()
                        .HasDatabaseName("ix_pessoas_tenant_id_documento");

                    b.HasIndex("TenantId", "Nome")
                        .HasDatabaseName("ix_pessoas_tenant_id_nome");

                    b.ToTable("pessoas", (string)null);
                });

            modelBuilder.Entity("Nexo.Api.Dominio.PessoaPapel", b =>
                {
                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<int>("Papel")
                        .HasColumnType("integer")
                        .HasColumnName("papel");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("PessoaId", "Papel")
                        .HasName("pk_pessoa_papeis");

                    b.HasIndex("TenantId", "Papel")
                        .HasDatabaseName("ix_pessoa_papeis_tenant_id_papel");

                    b.ToTable("pessoa_papeis", (string)null);
                });

            modelBuilder.Entity("Nexo.Api.Dominio.Recorrencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<Guid?>("CentroDeCustoId")
                        .HasColumnType("uuid")
                        .HasColumnName("centro_de_custo_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<int>("DiaDeVencimento")
                        .HasColumnType("integer")
                        .HasColumnName("dia_de_vencimento");

                    b.Property<DateOnly?>("FimEm")
                        .HasColumnType("date")
                        .HasColumnName("fim_em");

                    b.Property<int>("Frequencia")
                        .HasColumnType("integer")
                        .HasColumnName("frequencia");

                    b.Property<DateOnly>("InicioEm")
                        .HasColumnType("date")
                        .HasColumnName("inicio_em");

                    b.Property<int>("Natureza")
                        .HasColumnType("integer")
                        .HasColumnName("natureza");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Valor")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_recorrencias");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_recorrencias_categoria_id");

                    b.HasIndex("CentroDeCustoId")
                        .HasDatabaseName("ix_recorrencias_centro_de_custo_id");

                    b.HasIndex("PessoaId")
                        .HasDatabaseName("ix_recorrencias_pessoa_id");

                    b.HasIndex("TenantId", "Natureza", "Ativa")
                        .HasDatabaseName("ix_recorrencias_tenant_id_natureza_ativa");

                    b.ToTable("recorrencias", (string)null);
                });

            modelBuilder.Entity("Nexo.Api.Dominio.Renegociacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Desconto")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("desconto");

                    b.Property<decimal>("Juros")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("juros");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo");

                    b.Property<decimal>("Multa")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("multa");

                    b.Property<Guid>("OrigemId")
                        .HasColumnType("uuid")
                        .HasColumnName("origem_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_renegociacoes");

                    b.HasIndex("OrigemId")
                        .IsUnique()
                        .HasDatabaseName("ix_renegociacoes_origem_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_renegociacoes_tenant_id");

                    b.ToTable("renegociacoes", (string)null);
                });

            modelBuilder.Entity("Nexo.Api.Dominio.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Nexo.Api.Dominio.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<Guid?>("EmpresaPadraoId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_padrao_id");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_asp_net_users_tenant_id");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Nexo.Api.Dominio.ValorDoContrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo");

                    b.Property<decimal?>("Percentual")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("percentual");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Valor")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor");

                    b.Property<int>("VigenteDeAno")
                        .HasColumnType("integer")
                        .HasColumnName("vigente_de_ano");

                    b.Property<int>("VigenteDeMes")
                        .HasColumnType("integer")
                        .HasColumnName("vigente_de_mes");

                    b.HasKey("Id")
                        .HasName("pk_valores_de_contrato");

                    b.HasIndex("ContratoId")
                        .HasDatabaseName("ix_valores_de_contrato_contrato_id");

                    b.HasIndex("TenantId", "ContratoId", "VigenteDeAno", "VigenteDeMes")
                        .IsUnique()
                        .HasDatabaseName("ix_valores_de_contrato_tenant_id_contrato_id_vigente_de_ano_vi");

                    b.ToTable("valores_de_contrato", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Nexo.Api.Dominio.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Nexo.Api.Dominio.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Nexo.Api.Dominio.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Nexo.Api.Dominio.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("Nexo.Api.Dominio.Categoria", b =>
                {
                    b.HasOne("Nexo.Api.Dominio.Categoria", null)
                        .WithMany()
                        .HasForeignKey("PaiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categorias_categorias_pai_id");
                });

            modelBuilder.Entity("Nexo.Api.Dominio.Contrato", b =>
                {
                    b.HasOne("Nexo.Api.Dominio.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contratos_pessoas_pessoa_id");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Nexo.Api.Dominio.Empresa", b =>
                {
                    b.HasOne("Nexo.Api.Dominio.Empresa", "Matriz")
                        .WithMany("Filiais")
                        .HasForeignKey("MatrizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_empresas_empresas_matriz_id");

                    b.HasOne("Nexo.Api.Dominio.Tenant", "Tenant")
                        .WithMany("Empresas")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_empresas_tenants_tenant_id");

                    b.Navigation("Matriz");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Nexo.Api.Dominio.Lancamento", b =>
                {
                    b.HasOne("Nexo.Api.Dominio.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_lancamentos_categorias_categoria_id");

                    b.HasOne("Nexo.Api.Dominio.CentroDeCusto", "CentroDeCusto")
                        .WithMany()
                        .HasForeignKey("CentroDeCustoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_lancamentos_centros_de_custo_centro_de_custo_id");

                    b.HasOne("Nexo.Api.Dominio.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_lancamentos_contratos_contrato_id");

                    b.HasOne("Nexo.Api.Dominio.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lancamentos_pessoas_pessoa_id");

                    b.HasOne("Nexo.Api.Dominio.Recorrencia", null)
                        .WithMany()
                        .HasForeignKey("RecorrenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_lancamentos_recorrencias_recorrencia_id");

                    b.HasOne("Nexo.Api.Dominio.Lancamento", null)
                        .WithMany()
                        .HasForeignKey("RenegociadoDeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_lancamentos_lancamentos_renegociado_de_id");

                    b.Navigation("Categoria");

                    b.Navigation("CentroDeCusto");

                    b.Navigation("Contrato");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Nexo.Api.Dominio.MovimentoDeConta", b =>
                {
                    b.HasOne("Nexo.Api.Dominio.ContaBancaria", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimentos_de_conta_contas_bancarias_conta_id");

                    b.HasOne("Nexo.Api.Dominio.Lancamento", null)
                        .WithMany()
                        .HasForeignKey("LancamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_movimentos_de_conta_lancamentos_lancamento_id");

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("Nexo.Api.Dominio.Pessoa", b =>
                {
                    b.OwnsOne("Nexo.Api.Dominio.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<Guid>("PessoaId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("endereco_bairro");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("endereco_cep");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("endereco_cidade");

                            b1.Property<string>("Complemento")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("endereco_complemento");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("endereco_logradouro");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("endereco_numero");

                            b1.Property<string>("Uf")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("endereco_uf");

                            b1.HasKey("PessoaId");

                            b1.ToTable("pessoas");

                            b1.WithOwner()
                                .HasForeignKey("PessoaId")
                                .HasConstraintName("fk_pessoas_pessoas_id");
                        });

                    b.Navigation("Endereco")
                        .IsRequired();
                });

            modelBuilder.Entity("Nexo.Api.Dominio.PessoaPapel", b =>
                {
                    b.HasOne("Nexo.Api.Dominio.Pessoa", "Pessoa")
                        .WithMany("Papeis")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pessoa_papeis_pessoas_pessoa_id");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Nexo.Api.Dominio.Recorrencia", b =>
                {
                    b.HasOne("Nexo.Api.Dominio.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recorrencias_categorias_categoria_id");

                    b.HasOne("Nexo.Api.Dominio.CentroDeCusto", "CentroDeCusto")
                        .WithMany()
                        .HasForeignKey("CentroDeCustoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recorrencias_centros_de_custo_centro_de_custo_id");

                    b.HasOne("Nexo.Api.Dominio.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recorrencias_pessoas_pessoa_id");

                    b.Navigation("Categoria");

                    b.Navigation("CentroDeCusto");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Nexo.Api.Dominio.Renegociacao", b =>
                {
                    b.HasOne("Nexo.Api.Dominio.Lancamento", "Origem")
                        .WithMany()
                        .HasForeignKey("OrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_renegociacoes_lancamentos_origem_id");

                    b.Navigation("Origem");
                });

            modelBuilder.Entity("Nexo.Api.Dominio.Usuario", b =>
                {
                    b.HasOne("Nexo.Api.Dominio.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_users_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Nexo.Api.Dominio.ValorDoContrato", b =>
                {
                    b.HasOne("Nexo.Api.Dominio.Contrato", "Contrato")
                        .WithMany("Valores")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_valores_de_contrato_contratos_contrato_id");

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("Nexo.Api.Dominio.Contrato", b =>
                {
                    b.Navigation("Valores");
                });

            modelBuilder.Entity("Nexo.Api.Dominio.Empresa", b =>
                {
                    b.Navigation("Filiais");
                });

            modelBuilder.Entity("Nexo.Api.Dominio.Pessoa", b =>
                {
                    b.Navigation("Papeis");
                });

            modelBuilder.Entity("Nexo.Api.Dominio.Tenant", b =>
                {
                    b.Navigation("Empresas");
                });
#pragma warning restore 612, 618
        }
    }
}
