// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexo.Api.Dados;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexo.Api.Dados.Migracoes
{
    [DbContext(typeof(NexoDbContext))]
    [Migration("20260909003515_SegurancaPorLinha")]
    partial class SegurancaPorLinha
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexo.Api.Dominio.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("MatrizId")
                        .HasColumnType("uuid")
                        .HasColumnName("matriz_id");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razao_social");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_empresas");

                    b.HasIndex("MatrizId")
                        .HasDatabaseName("ix_empresas_matriz_id");

                    b.HasIndex("TenantId", "Cnpj")
                        .IsUnique()
                        .HasDatabaseName("ix_empresas_tenant_id_cnpj");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("Nexo.Api.Dominio.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Nexo.Api.Dominio.Empresa", b =>
                {
                    b.HasOne("Nexo.Api.Dominio.Empresa", "Matriz")
                        .WithMany("Filiais")
                        .HasForeignKey("MatrizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_empresas_empresas_matriz_id");

                    b.HasOne("Nexo.Api.Dominio.Tenant", "Tenant")
                        .WithMany("Empresas")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_empresas_tenants_tenant_id");

                    b.Navigation("Matriz");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Nexo.Api.Dominio.Empresa", b =>
                {
                    b.Navigation("Filiais");
                });

            modelBuilder.Entity("Nexo.Api.Dominio.Tenant", b =>
                {
                    b.Navigation("Empresas");
                });
#pragma warning restore 612, 618
        }
    }
}
